/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ptud;

import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author TomTom
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public void scaleimg(JLabel label, URL url) {
//        scale image, icon
        var icon = new ImageIcon(url);
        Image img = icon.getImage();
        Image imgScl;
        imgScl = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon sclit = new ImageIcon(imgScl);
        label.setIcon(sclit);
    }
    public void menuItemClick(JPanel panel) {
        Color color = new Color(51, 51, 255);
        
        // Reset color menu item
        qlnsItem.setBackground(color);
        qlspItem.setBackground(color);
       
        // Set the new color to the component
        panel.setBackground(new Color(0, 0, 204));
    }
    
    public Main() {
        initComponents();
        
        scaleimg(avatarLabel,getClass().getResource("/assets/images/avataruser1.jpg"));
        scaleimg(qlnsIcon, getClass().getResource("/assets/icons/qlnv.png"));
        scaleimg(qlspIcon, getClass().getResource("/assets/icons/qlsp.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AsidePanel = new javax.swing.JPanel();
        avatarLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        qlnsItem = new javax.swing.JPanel();
        qlnsIcon = new javax.swing.JLabel();
        qlnsText = new javax.swing.JLabel();
        qlspItem = new javax.swing.JPanel();
        qlspIcon = new javax.swing.JLabel();
        qlspText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        AsidePanel.setBackground(new java.awt.Color(102, 102, 255));
        AsidePanel.setPreferredSize(new java.awt.Dimension(200, 600));

        avatarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/avataruser1.jpg"))); // NOI18N
        avatarLabel.setText("jLabel1");
        avatarLabel.setPreferredSize(new java.awt.Dimension(120, 100));

        qlnsItem.setBackground(new java.awt.Color(51, 51, 255));
        qlnsItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        qlnsItem.setPreferredSize(new java.awt.Dimension(200, 40));
        qlnsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlnsItemMouseClicked(evt);
            }
        });

        qlnsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/qlnv.png"))); // NOI18N
        qlnsIcon.setText("jLabel1");

        qlnsText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qlnsText.setForeground(new java.awt.Color(0, 0, 0));
        qlnsText.setText("Quản lý nhân sự");
        qlnsText.setRequestFocusEnabled(false);

        javax.swing.GroupLayout qlnsItemLayout = new javax.swing.GroupLayout(qlnsItem);
        qlnsItem.setLayout(qlnsItemLayout);
        qlnsItemLayout.setHorizontalGroup(
            qlnsItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlnsItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qlnsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qlnsText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qlnsItemLayout.setVerticalGroup(
            qlnsItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qlnsItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(qlnsItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qlnsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qlnsText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        qlspItem.setBackground(new java.awt.Color(51, 51, 255));
        qlspItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        qlspItem.setPreferredSize(new java.awt.Dimension(200, 40));

        qlspIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/qlnv.png"))); // NOI18N
        qlspIcon.setText("jLabel1");

        qlspText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qlspText.setForeground(new java.awt.Color(0, 0, 0));
        qlspText.setText("Quản lý sản phẩm");
        qlspText.setRequestFocusEnabled(false);
        qlspText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlspTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout qlspItemLayout = new javax.swing.GroupLayout(qlspItem);
        qlspItem.setLayout(qlspItemLayout);
        qlspItemLayout.setHorizontalGroup(
            qlspItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlspItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qlspIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qlspText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qlspItemLayout.setVerticalGroup(
            qlspItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qlspItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(qlspItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qlspIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qlspText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout AsidePanelLayout = new javax.swing.GroupLayout(AsidePanel);
        AsidePanel.setLayout(AsidePanelLayout);
        AsidePanelLayout.setHorizontalGroup(
            AsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsidePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsidePanelLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(qlnsItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(qlspItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, Short.MAX_VALUE)
        );
        AsidePanelLayout.setVerticalGroup(
            AsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsidePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(qlnsItem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(qlspItem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AsidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AsidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qlnsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlnsItemMouseClicked
        // TODO add your handling code here:
        menuItemClick(qlnsItem);
    }//GEN-LAST:event_qlnsItemMouseClicked

    private void qlspTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlspTextMouseClicked
        // TODO add your handling code here:
        menuItemClick(qlspItem);
    }//GEN-LAST:event_qlspTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AsidePanel;
    private javax.swing.JLabel avatarLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel qlnsIcon;
    private javax.swing.JPanel qlnsItem;
    private javax.swing.JLabel qlnsText;
    private javax.swing.JLabel qlspIcon;
    private javax.swing.JPanel qlspItem;
    private javax.swing.JLabel qlspText;
    // End of variables declaration//GEN-END:variables
}

